add solution for 5-module 2-task with unknown errors in some tests
js-tasks-ru/nodejs-20200914-2_ushev-s90 pull request #6
Opened 2020-10-06 21:29 UTC by ushev-s

Во время проверочного теста кода выпадают непонятные ошибки. Не могли бы вы взглянуть на код?

2020-10-06 21:46 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-10-07 20:20 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Файловый сервер - запись файла
+ возвращается ошибка 409 при создании файла, который есть
+ если тело запроса пустое файл не перезаписывается
+ при попытке создания слишком большого файла - ошибка 413
+ успешное создание файла
+ файл не должен оставаться на диске при обрыве соединения
+ если путь вложенный - возвращается ошибка 400
```

Добавляю преподавателя (@RidgeA) для код-ревью, посмотрим что он скажет :)

2020-10-07 20:34 UTC, RidgeA requested changes

2020-10-07 20:34 UTC, RidgeA commented on 05-http-server-streams/02-file-server-post/server.js
> +        .on('data', (chunk) => {
В данном случае лучше всего воспользоваться методо `pipe` для передачи данных из стрима в стрим, например так: `req.pipe(limitedStream).pipe(writeStream)`

При этом надо подписаться на нужные события (например события ошибок) что бы отловить различные ошибочные ситуации (файл уже существует, превышен лимит и т. д)

Вычитывая весь запрос вы сохраняете его в памяти и это может привести к тому, что память переполнится, ведь проверка на то, превышает ли размер тела лимит происходит уже после вычитки всего тела запроса.

2020-10-07 20:34 UTC, RidgeA commented on 05-http-server-streams/02-file-server-post/server.js
> +        fs.stat(filepath, (err) => {
Проверку на отсутствие файла так лучше не делать, ведь при определенных обстоятельствах (которые сложно воспроизвести в тестах) может сложиться такая ситуация, что в одном запросе пройдет проверка что файла еще нет, а в то же время (почти в то же время) другой запрос создаст файл с таким именем и все-равно выйдет ошибка при записи. 
Факт наличия файла улчше проверить по ошибке, которую может вернуть Writable стрим, если его открыть с правильными флагами

2020-10-07 21:25 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
Файловый сервер - запись файла
+ возвращается ошибка 409 при создании файла, который есть
+ если тело запроса пустое файл не перезаписывается
+ при попытке создания слишком большого файла - ошибка 413
+ успешное создание файла
+ если путь вложенный - возвращается ошибка 400
- файл не должен оставаться на диске при обрыве соединения
```

2020-10-07 22:27 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
Файловый сервер - запись файла
+ возвращается ошибка 409 при создании файла, который есть
+ если тело запроса пустое файл не перезаписывается
+ при попытке создания слишком большого файла - ошибка 413
+ успешное создание файла
+ если путь вложенный - возвращается ошибка 400
- файл не должен оставаться на диске при обрыве соединения
```

2020-10-07 22:41 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
Файловый сервер - запись файла
+ возвращается ошибка 409 при создании файла, который есть
+ если тело запроса пустое файл не перезаписывается
+ при попытке создания слишком большого файла - ошибка 413
+ успешное создание файла
+ если путь вложенный - возвращается ошибка 400
- файл не должен оставаться на диске при обрыве соединения
```

2020-10-07 22:48 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
Файловый сервер - запись файла
+ возвращается ошибка 409 при создании файла, который есть
+ если тело запроса пустое файл не перезаписывается
+ при попытке создания слишком большого файла - ошибка 413
+ успешное создание файла
+ если путь вложенный - возвращается ошибка 400
- файл не должен оставаться на диске при обрыве соединения
```

2020-10-08 20:59 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
Файловый сервер - запись файла
+ возвращается ошибка 409 при создании файла, который есть
+ если тело запроса пустое файл не перезаписывается
+ при попытке создания слишком большого файла - ошибка 413
+ успешное создание файла
+ если путь вложенный - возвращается ошибка 400
- файл не должен оставаться на диске при обрыве соединения
```

2020-10-08 21:22 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @RidgeA

2020-10-09 07:38 UTC, RidgeA approved these changes

2020-10-09 07:38 UTC, merged